version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  user_service:
    build: ./user_service/app/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/user_db
    ports:
      - "8000:8000"
      - "50051:50051"

  todo_service:
    build: ./todo_service/app/
    depends_on:
      - postgres
      - user_service
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/todo_db
    ports:
      - "8001:8001"
      - "50052:50052"

volumes:
  postgres_data:
